<template>
  <UModal 
    :title="$t('component.subCategory.addModal.title')"
    :description="$t('component.subCategory.addModal.description')"
    v-model:open="open" 
    :ui="{ 
      content: 'sm:max-w-md', 
      overlay: 'bg-black/40',
      footer: 'justify-end'
    }"
  >
    <template #body>
      <UForm id="add-sub-category-form" :schema="schema" :state="form" @submit="handleSubmit" class="space-y-3">
        <UFormField :label="$t('common.category')" name="categoryId" required>
          <USelectMenu
            v-model="selectedCategory"
            :items="categoryOptions"
            searchable
            :searchable-placeholder="$t('component.subCategory.addModal.searchCategory')"
            :placeholder="$t('component.subCategory.addModal.selectCategory')"
            class="w-full"
          />
        </UFormField>
        <UFormField :label="$t('common.code')" name="code">
          <UInput v-model="form.code" :placeholder="$t('common.autoGenerated')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.name')" name="name" required>
          <UInput v-model="form.name" :placeholder="$t('component.subCategory.addModal.namePlaceholder')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.description')" name="description">
          <UTextarea v-model="form.description" :placeholder="$t('common.enterDescription')" class="w-full" :rows="3" />
        </UFormField>
      </UForm>
    </template>
    <template #footer>
      <div class="flex justify-end items-center gap-2 w-full">
        <UButton :label="$t('common.cancel')" @click="() => { open = false }" color="neutral" variant="outline" />
        <UButton :label="$t('common.save')" type="submit" form="add-sub-category-form" color="primary" :loading="isSubmitting" />
      </div>
    </template>
  </UModal>
</template>

<script setup lang="ts">
import { z } from 'zod'
import { subCategoryService } from '~/services/sub-category-service'
import { categoryService } from '~/services/category-service'
import type { SubCategoryPayload } from '~/types/sub-category'

const { t } = useI18n()
const open = defineModel<boolean>({ default: false })
const emit = defineEmits<{ created: [] }>()
const toast = useToast()
const isSubmitting = ref(false)

const categoryOptions = ref<{ label: string; value: number }[]>([])

const selectedCategory = computed({
  get: () => categoryOptions.value.find((c) => c.value === form.categoryId),
  set: (val) => {
    form.categoryId = val?.value as unknown as number
  }
})

const schema = z.object({
  categoryId: z.number().int().positive(t('component.subCategory.addModal.categoryRequired')),
  code: z.string().optional().or(z.literal('')),
  name: z.string().min(1, t('common.nameRequired')),
  description: z.string().optional().or(z.literal('')),
})

const form = reactive<SubCategoryPayload>({
  code: '',
  name: '',
  description: '',
  categoryId: undefined as unknown as number,
})

const resetForm = () => {
  form.code = ''
  form.name = ''
  form.description = ''
  form.categoryId = undefined as unknown as number
}

const fetchCategories = async () => {
  const response = await categoryService.getList()
  if (response.success) {
    categoryOptions.value = response.data.map((c) => ({
      label: c.name,
      value: c.id,
    }))
  }
}

const handleSubmit = async () => {
  isSubmitting.value = true
  try {
    const response = await subCategoryService.create(form)
    if (response.success) {
      toast.add({
        title: t('component.subCategory.addModal.success'),
        color: 'success',
        icon: 'i-lucide-circle-check'
      })
      emit('created')
      open.value = false
      resetForm()
    }
  } finally {
    isSubmitting.value = false
  }
}

watch(open, (val) => {
  if (val) {
    fetchCategories()
  } else {
    resetForm()
  }
})
</script>
