<template>
  <UModal 
    :title="$t('component.subCategory.updateModal.title')"
    :description="$t('component.subCategory.updateModal.description')"
    v-model:open="open" 
    :ui="{ 
      content: 'sm:max-w-md', 
      overlay: 'bg-black/40',
      footer: 'justify-end'
    }"
  >
    <template #body>
      <UForm id="update-sub-category-form" :schema="schema" :state="form" @submit="handleSubmit" class="space-y-3">
        <UFormField :label="$t('common.category')" name="categoryId" required>
          <USelectMenu
            v-model="selectedCategory"
            :items="categoryOptions"
            searchable
            :searchable-placeholder="$t('component.subCategory.updateModal.searchCategory')"
            :placeholder="$t('component.subCategory.updateModal.selectCategory')"
            class="w-full"
          />
        </UFormField>
        <UFormField :label="$t('common.code')" name="code">
          <UInput v-model="form.code" :placeholder="$t('common.autoGenerated')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.name')" name="name" required>
          <UInput v-model="form.name" :placeholder="$t('component.subCategory.updateModal.namePlaceholder')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.description')" name="description">
          <UTextarea v-model="form.description" :placeholder="$t('common.enterDescription')" class="w-full" :rows="3" />
        </UFormField>
      </UForm>
    </template>
    <template #footer>
      <div class="flex justify-end items-center gap-2 w-full">
        <UButton :label="$t('common.cancel')" @click="() => { open = false }" color="neutral" variant="outline" />
        <UButton
          type="submit"
          form="update-sub-category-form"
          color="primary"
          :loading="isSubmitting"
        >
          {{ $t('common.saveChanges') }}
        </UButton>
      </div>
    </template>
  </UModal>
</template>

<script setup lang="ts">
import { z } from 'zod'
import { subCategoryService } from '~/services/sub-category-service'
import { categoryService } from '~/services/category-service'
import type { SubCategory, SubCategoryPayload } from '~/types/sub-category'

const { t } = useI18n()

const open = defineModel<boolean>({ default: false })

const props = defineProps<{
  subCategory: SubCategory | null
}>()

const emit = defineEmits<{ updated: [] }>()
const toast = useToast()
const isSubmitting = ref(false)

const categoryOptions = ref<{ label: string; value: number }[]>([])

const selectedCategory = computed({
  get: () => categoryOptions.value.find((c) => c.value === form.categoryId),
  set: (val) => {
    form.categoryId = val?.value as unknown as number
  }
})

const schema = z.object({
  categoryId: z.number().int().positive(t('component.subCategory.updateModal.categoryRequired')),
  code: z.string().optional().or(z.literal('')),
  name: z.string().min(1, t('common.nameRequired')),
  description: z.string().optional().or(z.literal('')),
})

const form = reactive<SubCategoryPayload>({
  code: '',
  name: '',
  description: '',
  categoryId: undefined as unknown as number,
})

const fetchCategories = async () => {
  const response = await categoryService.getList()
  if (response.success) {
    categoryOptions.value = response.data.map((c) => ({
      label: c.name,
      value: c.id,
    }))
  }
}

const populateForm = () => {
  if (props.subCategory) {
    form.code = props.subCategory.code || ''
    form.name = props.subCategory.name
    form.description = props.subCategory.description || ''
    form.categoryId = props.subCategory.category?.id || props.subCategory.categoryId
  }
}

const handleSubmit = async () => {
  if (!props.subCategory) return
  isSubmitting.value = true
  try {
    const response = await subCategoryService.update(props.subCategory.id, form)
    if (response.success) {
      toast.add({
        title: t('component.subCategory.updateModal.success'),
        color: 'success',
        icon: 'i-lucide-circle-check'
      })
      emit('updated')
      open.value = false
    }
  } finally {
    isSubmitting.value = false
  }
}

watch(open, async (val) => {
  if (val) {
    await fetchCategories()
    populateForm()
  }
})
</script>
