<template>
  <UModal 
    :title="$t('component.category.addModal.title')"
    :description="$t('component.category.addModal.description')"
    v-model:open="open" 
    :ui="{ 
      content: 'sm:max-w-md', 
      overlay: 'bg-black/40',
      footer: 'justify-end'
    }"
  >
    <template #body>
      <UForm id="add-category-form" :schema="schema" :state="form" @submit="handleSubmit" class="space-y-3">
        <UFormField :label="$t('common.code')" name="code">
          <UInput v-model="form.code" :placeholder="$t('common.autoGenerated')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.name')" name="name" required>
          <UInput v-model="form.name" :placeholder="$t('component.category.addModal.namePlaceholder')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.description')" name="description">
          <UTextarea v-model="form.description" :placeholder="$t('common.enterDescription')" class="w-full" :rows="3" />
        </UFormField>
      </UForm>
    </template>
    <template #footer>
      <div class="flex justify-end items-center gap-2 w-full">
        <UButton :label="$t('common.cancel')" @click="open = false" color="neutral" variant="outline" />
        <UButton
          type="submit"
          form="add-category-form"
          color="primary"
          :loading="isSubmitting"
        >
          {{ $t('component.category.addModal.submit') }}
        </UButton>
      </div>
    </template>
  </UModal>
</template>

<script setup lang="ts">
import { z } from 'zod'
import { categoryService } from '~/services/category-service'
import type { CategoryPayload } from '~/types/category'

const { t } = useI18n()

const open = defineModel<boolean>({ default: false })
const emit = defineEmits<{ created: [] }>()
const toast = useToast()
const isSubmitting = ref(false)

const schema = z.object({
  code: z.string().optional().or(z.literal('')),
  name: z.string().min(1, t('common.nameRequired')),
  description: z.string().optional().or(z.literal('')),
})

const form = reactive<CategoryPayload>({
  code: '',
  name: '',
  description: '',
})

const resetForm = () => {
  form.code = ''
  form.name = ''
  form.description = ''
}

const handleSubmit = async () => {
  isSubmitting.value = true
  try {
    const response = await categoryService.create(form)
    if (response.success) {
      toast.add({
        title: t('component.category.addModal.success'),
        color: 'success',
        icon: 'i-lucide-circle-check'
      })
      emit('created')
      open.value = false
      resetForm()
    }
  } finally {
    isSubmitting.value = false
  }
}

watch(open, (val) => {
  if (!val) resetForm()
})
</script>
