<template>
  <UModal 
    :title="$t('component.category.updateModal.title')"
    :description="$t('component.category.updateModal.description')"
    v-model:open="open" 
    :ui="{ 
      content: 'sm:max-w-md', 
      overlay: 'bg-black/40',
      footer: 'justify-end'
    }"
  >
    <template #body>
      <UForm id="update-category-form" :schema="schema" :state="form" @submit="handleSubmit" class="space-y-3">
        <UFormField :label="$t('common.code')" name="code">
          <UInput v-model="form.code" :placeholder="$t('common.autoGenerated')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.name')" name="name" required>
          <UInput v-model="form.name" :placeholder="$t('component.category.updateModal.namePlaceholder')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.description')" name="description">
          <UTextarea v-model="form.description" :placeholder="$t('common.enterDescription')" class="w-full" :rows="3" />
        </UFormField>
      </UForm>
    </template>
    <template #footer>
      <div class="flex justify-end items-center gap-2 w-full">
        <UButton :label="$t('common.cancel')" @click="() => { open = false }" color="neutral" variant="outline" />
        <UButton :label="$t('common.save')" type="submit" form="update-category-form" color="primary" :loading="isSubmitting" />
      </div>
    </template>
  </UModal>
</template>

<script setup lang="ts">
import { z } from 'zod'
import { categoryService } from '~/services/category-service'
import type { Category, CategoryPayload } from '~/types/category'

const { t } = useI18n()

const open = defineModel<boolean>({ default: false })

const props = defineProps<{
  category: Category | null
}>()

const emit = defineEmits<{ updated: [] }>()
const toast = useToast()
const isSubmitting = ref(false)

const schema = z.object({
  code: z.string().optional().or(z.literal('')),
  name: z.string().min(1, t('common.nameRequired')),
  description: z.string().optional().or(z.literal('')),
})

const form = reactive<CategoryPayload>({
  code: '',
  name: '',
  description: '',
})

const populateForm = () => {
  if (props.category) {
    form.code = props.category.code || ''
    form.name = props.category.name
    form.description = props.category.description || ''
  }
}

const handleSubmit = async () => {
  if (!props.category) return
  isSubmitting.value = true
  try {
    const response = await categoryService.update(props.category.id, form)
    if (response.success) {
      toast.add({
        title: t('component.category.updateModal.success'),
        color: 'success',
        icon: 'i-lucide-circle-check'
      })
      emit('updated')
      open.value = false
    }
  } finally {
    isSubmitting.value = false
  }
}

watch(open, (val) => {
  if (val) {
    populateForm()
  }
})
</script>
