<template>
  <UModal
    v-model:open="open"
    :title="isEdit ? $t('pages.inventory.item.editTitle') : $t('pages.inventory.item.addTitle')"
    :ui="{ content: 'sm:max-w-md', overlay: 'bg-black/40', footer: 'justify-end' }"
  >
    <template #body>
      <UForm id="inventory-form" :schema="schema" :state="state" class="space-y-4 w-full" @submit="onSubmit">
        <UFormField :label="$t('common.name')" name="name" required>
          <UInput v-model="state.name" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.code')" name="code">
          <UInput v-model="state.code" :placeholder="$t('common.autoGenerated')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.description')" name="description">
          <UTextarea v-model="state.description" class="w-full" :rows="3" />
        </UFormField>
      </UForm>
    </template>

    <template #footer>
      <UButton :label="$t('common.cancel')" color="neutral" variant="outline" :disabled="saving" @click="() => { open = false }" />
      <UButton :label="$t('common.save')" color="primary" type="submit" form="inventory-form" :loading="saving" />
    </template>
  </UModal>
</template>

<script setup lang="ts">
import { z } from 'zod'
import { inventoryService } from '~/services/inventory-service'
import type { Inventory } from '~/types/inventory'

const { t } = useI18n()
const toast = useToast()

const props = defineProps<{ product?: Inventory | null }>()
const open = defineModel<boolean>({ default: false })
const emit = defineEmits<{ saved: [] }>()

const isEdit = computed(() => !!props.product)
const saving = ref(false)

const schema = z.object({
  name: z.string().trim().min(1, t('common.nameRequired')),
  code: z.string().optional().or(z.literal('')),
  description: z.string().optional().or(z.literal(''))
})

const state = reactive({ name: '', code: '', description: '' })

const onSubmit = async () => {
  saving.value = true
  try {
    const payload = { name: state.name, code: state.code || null, description: state.description || null }
    const res = props.product
      ? await inventoryService.update(props.product.id, payload)
      : await inventoryService.create(payload)
    if (res.success) {
      toast.add({ title: t('common.save'), color: 'success', icon: 'i-lucide-circle-check' })
      emit('saved')
      open.value = false
    } else {
      toast.add({ title: res.message || 'Error occurred', color: 'error', icon: 'i-lucide-circle-alert' })
    }
  } finally {
    saving.value = false
  }
}

watch(open, (val) => {
  if (val) {
    state.name = props.product?.name || ''
    state.code = props.product?.code || ''
    state.description = props.product?.description || ''
  }
})
</script>
