<template>
  <UModal 
    :title="$t('component.branch.updateModal.title')"
    :description="$t('component.branch.updateModal.description')"
    v-model:open="open" 
    :ui="{ 
      content: 'sm:max-w-md', 
      overlay: 'bg-black/40',
      footer: 'justify-end'
    }"
  >
    <template #body>
      <UForm id="update-branch-form" :schema="schema" :state="form" @submit="handleSubmit" class="space-y-3">
        <UFormField :label="$t('common.code')" name="code">
          <UInput v-model="form.code" :placeholder="$t('common.autoGenerated')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.name')" name="name" required>
          <UInput v-model="form.name" :placeholder="$t('component.branch.updateModal.namePlaceholder')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.description')" name="description">
          <UTextarea v-model="form.description" :placeholder="$t('common.enterDescription')" class="w-full" :rows="3" />
        </UFormField>
        <UFormField :label="$t('common.address')" name="address">
          <UTextarea v-model="form.address" :placeholder="$t('component.branch.updateModal.addressPlaceholder')" class="w-full" :rows="2" />
        </UFormField>
        <UFormField :label="$t('common.email')" name="email">
          <UInput v-model="form.email" type="email" :placeholder="$t('component.branch.updateModal.emailPlaceholder')" class="w-full" />
        </UFormField>
        <UFormField :label="$t('common.phone')" name="phone">
          <UInput v-model="form.phone" :placeholder="$t('component.branch.updateModal.phonePlaceholder')" class="w-full" />
        </UFormField>
      </UForm>
    </template>
    <template #footer>
      <div class="flex justify-end items-center gap-2 w-full">
        <UButton :label="$t('common.cancel')" @click="() => { open = false }" color="neutral" variant="outline" />
        <UButton :label="$t('common.save')" type="submit" form="update-branch-form" color="primary" :loading="isSubmitting" />
      </div>
    </template>
  </UModal>
</template>

<script setup lang="ts">
import { z } from 'zod'
import { branchService } from '~/services/branch-service'
import type { Branch, BranchPayload } from '~/types/branch'

const { t } = useI18n()

const open = defineModel<boolean>({ default: false })

const props = defineProps<{
  branch: Branch | null
}>()

const emit = defineEmits<{ updated: [] }>()
const toast = useToast()
const isSubmitting = ref(false)

const schema = z.object({
  code: z.string().optional().or(z.literal('')),
  name: z.string().min(1, t('common.nameRequired')),
  description: z.string().optional().or(z.literal('')),
  address: z.string().optional().or(z.literal('')),
  email: z.string().email(t('component.branch.updateModal.emailInvalid')).optional().or(z.literal('')),
  phone: z.string().optional().or(z.literal('')),
})

const form = reactive<BranchPayload>({
  code: '',
  name: '',
  description: '',
  address: '',
  email: '',
  phone: '',
})

const populateForm = () => {
  if (props.branch) {
    form.code = props.branch.code
    form.name = props.branch.name
    form.description = props.branch.description || ''
    form.address = props.branch.address || ''
    form.email = props.branch.email || ''
    form.phone = props.branch.phone || ''
  }
}

const handleSubmit = async () => {
  if (!props.branch) return
  isSubmitting.value = true
  try {
    const response = await branchService.update(props.branch.id, form)
    if (response.success) {
      toast.add({
        title: t('component.branch.updateModal.success'),
        color: 'success',
        icon: 'i-lucide-circle-check'
      })
      emit('updated')
      open.value = false
    }
  } finally {
    isSubmitting.value = false
  }
}

watch(open, (val) => {
  if (val) {
    populateForm()
  }
})
</script>
