<template>
  <div class="space-y-6">
    <Header :title="$t('pages.inventory.create.title')" :description="$t('pages.inventory.create.description')" />

    <UCard class="w-full">
      <div class="w-full mb-4">
        <UButton :label="$t('common.back')" to="/inventory" color="neutral" icon="i-lucide-arrow-left" variant="link" />
      </div>

      <UForm id="inv-create-form" :schema="schema" :state="form" @submit="onSubmit">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-x-6 gap-y-4">

          <!-- ═══ Column 1: Photo ═══ -->
          <div class="space-y-4">
            <div>
              <div class="flex justify-between mb-1.5">
                <label class="text-sm font-medium text-neutral-700">{{ $t('pages.inventory.item.photo') }}</label>
                <UButton icon="i-lucide-camera" color="primary" variant="soft" size="xs" @click="() => { showCamera = true }">{{ $t('pages.asset.create.takePhoto') }}</UButton>
              </div>
              <div v-if="previewUrl" class="relative inline-block w-full aspect-square">
                <NuxtImg :src="previewUrl" class="w-full h-full rounded-lg object-cover border border-neutral-200" />
                <UButton icon="i-lucide-x" color="error" variant="solid" size="xs" class="absolute top-1 right-1 rounded-full" @click="removeImage" />
              </div>
              <div v-else class="flex flex-col items-center justify-center w-full aspect-square border-2 border-dashed border-neutral-200 rounded-lg cursor-pointer hover:border-primary transition-colors" @click="triggerFileInput">
                <UIcon name="i-lucide-upload" class="w-8 h-8 text-neutral-400 mb-2" />
                <span class="text-sm text-neutral-500">{{ $t('pages.asset.create.dropImage') }}</span>
                <span class="text-xs text-neutral-400 mt-1">{{ $t('pages.asset.create.imageHint') }}</span>
              </div>
              <div v-if="isUploading" class="mt-2 flex items-center gap-2 text-sm text-neutral-500">
                <UIcon name="i-lucide-loader-2" class="w-4 h-4 animate-spin" /> {{ $t('pages.asset.create.uploading') }}
              </div>
              <input ref="fileInput" type="file" class="hidden" accept="image/*" @change="onFileChange">
              <CameraModal v-model="showCamera" @captured="onCaptured" />
            </div>

            <AttachmentManager v-model="attachments" @change="(ids) => { attachmentIds = ids }" />
          </div>

          <!-- ═══ Column 2: Content ═══ -->
          <div class="space-y-4">
            <UFormField :label="$t('common.name')" name="name" required>
              <UInput v-model="form.name" class="w-full" />
            </UFormField>

            <UFormField :label="$t('common.code')" name="code">
              <UInput v-model="form.code" :placeholder="$t('common.autoGenerated')" class="w-full" />
            </UFormField>

            <UFormField :label="$t('common.category')" name="categoryId">
              <div class="flex items-center gap-2">
                <USelectMenu v-model="selectedCategory" :items="categoryOptions" searchable :searchable-placeholder="$t('pages.asset.create.searchCategory')" :placeholder="$t('pages.asset.create.selectCategory')" class="w-full" />
                <UButton icon="i-lucide-plus" color="primary" variant="soft" size="sm" square @click="() => { showAddCategory = true }" />
              </div>
            </UFormField>

            <UFormField :label="$t('common.subCategory')" name="subCategoryId">
              <div class="flex items-center gap-2">
                <USelectMenu v-model="selectedSubCategory" :items="subCategoryOptions" searchable :searchable-placeholder="$t('pages.asset.create.searchSubCategory')" :placeholder="$t('pages.asset.create.selectSubCategory')" :disabled="!selectedCategoryId" class="w-full" />
                <UButton icon="i-lucide-plus" color="primary" variant="soft" size="sm" square @click="() => { showAddSubCategory = true }" />
              </div>
            </UFormField>

            <UFormField :label="$t('pages.inventory.unit.label')" name="unit">
              <USelectMenu v-model="form.unit" :items="unitOptions" value-key="value" :placeholder="$t('pages.inventory.unit.placeholder')" class="w-full" />
            </UFormField>

            <UFormField :label="$t('common.description')" name="description">
              <UTextarea v-model="form.description" class="w-full" :rows="3" />
            </UFormField>

            <div>
              <div class="flex items-center justify-between mb-1.5">
                <label class="text-sm font-medium text-neutral-700">{{ $t('pages.inventory.item.labels') }}</label>
                <UButton icon="i-lucide-plus" color="primary" variant="soft" size="xs" @click="addLabel">{{ $t('common.add') }}</UButton>
              </div>
              <div v-if="labels.length === 0" class="text-sm text-neutral-400 py-3 text-center border border-dashed border-neutral-200 rounded-lg">{{ $t('pages.inventory.create.noLabels') }}</div>
              <div v-else class="space-y-2">
                <div v-for="(label, i) in labels" :key="i" class="flex items-center gap-2">
                  <UInputMenu v-model="label.key" :items="availableLabelKeys" placeholder="Key" class="w-full" />
                  <UInput v-model="label.value" placeholder="Value" class="w-full" />
                  <UButton icon="i-lucide-trash" color="error" variant="soft" size="sm" square @click="() => { labels.splice(i, 1) }" />
                </div>
              </div>
            </div>
          </div>

          <!-- ═══ Column 3: Variants + initial stock ═══ -->
          <div class="space-y-3">
            <div class="flex items-center justify-between">
              <label class="text-sm font-medium text-neutral-700 flex items-center gap-1.5">
                <UIcon name="i-lucide-package" class="w-4 h-4 text-primary-500" /> {{ $t('pages.inventory.variant.title') }}
              </label>
              <UButton icon="i-lucide-plus" color="primary" variant="soft" size="xs" @click="addVariant">{{ $t('pages.inventory.variant.add') }}</UButton>
            </div>
            <div v-if="variants.length === 0" class="text-sm text-neutral-400 py-6 text-center border-2 border-dashed border-neutral-200 rounded-lg">{{ $t('pages.inventory.create.noVariants') }}</div>
            <div v-else class="space-y-3">
              <div v-for="(v, vi) in variants" :key="vi" class="p-3 rounded-lg border border-neutral-200 space-y-2.5">
                <div class="flex items-center gap-2">
                  <UInput v-model="v.name" :placeholder="$t('pages.inventory.create.variantName')" size="sm" class="w-full" />
                  <UButton icon="i-lucide-trash" color="error" variant="soft" size="xs" square @click="() => { variants.splice(vi, 1) }" />
                </div>
                <UInput v-model="v.code" :placeholder="$t('common.code')" size="sm" class="w-full" />
                <div class="pt-1">
                  <div class="grid grid-cols-[1fr_auto_auto] gap-x-2 gap-y-1 items-center text-xs">
                    <span class="text-neutral-400 uppercase tracking-wider font-semibold">{{ $t('pages.inventory.create.initialStock') }}</span>
                    <span class="text-neutral-400 text-center w-16">{{ $t('pages.inventory.condition.new') }}</span>
                    <span class="text-neutral-400 text-center w-16">{{ $t('pages.inventory.condition.used') }}</span>
                    <template v-for="b in branchList" :key="b.id">
                      <span class="text-neutral-600 truncate">{{ b.name }}</span>
                      <UInput v-model.number="v.stock[b.id]!.new" type="number" :min="0" size="sm" class="w-16" />
                      <UInput v-model.number="v.stock[b.id]!.used" type="number" :min="0" size="sm" class="w-16" />
                    </template>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="flex justify-end gap-2 pt-4 mt-6 border-t border-neutral-100">
          <UButton type="button" color="neutral" variant="outline" to="/inventory">{{ $t('common.cancel') }}</UButton>
          <UButton type="submit" color="primary" :loading="isSubmitting">{{ $t('common.save') }}</UButton>
        </div>
      </UForm>
    </UCard>

    <CategoryAddModal v-model="showAddCategory" @created="onCategoryCreated" />
    <SubCategoryAddModal v-model="showAddSubCategory" @created="onSubCategoryCreated" />
  </div>
</template>

<script setup lang="ts">
import { z } from 'zod'
import { inventoryService } from '~/services/inventory-service'
import { categoryService } from '~/services/category-service'
import { subCategoryService } from '~/services/sub-category-service'
import { branchService } from '~/services/branch-service'
import type { InventoryVariantInput } from '~/types/inventory'
import type { Attachment } from '~/types/attachment'

definePageMeta({ layout: 'dashboard' })

const { t } = useI18n()
const toast = useToast()

const schema = z.object({ name: z.string().trim().min(1, t('common.nameRequired')) })
const form = reactive<{ name: string, code: string, description: string, image: string | null, unit: string, subCategoryId?: number }>({
  name: '', code: '', description: '', image: null, unit: 'Pcs', subCategoryId: undefined
})

// ── Category / sub-category (with inline add, like asset) ──────────────
const categoryOptions = ref<{ label: string, value: number }[]>([])
const subCategoryOptions = ref<{ label: string, value: number }[]>([])
const selectedCategoryId = ref<number | undefined>(undefined)
const showAddCategory = ref(false)
const showAddSubCategory = ref(false)

const selectedCategory = computed({
  get: () => categoryOptions.value.find(c => c.value === selectedCategoryId.value),
  set: (val) => { selectedCategoryId.value = val?.value }
})
const selectedSubCategory = computed({
  get: () => subCategoryOptions.value.find(s => s.value === form.subCategoryId),
  set: (val) => { form.subCategoryId = val?.value }
})

const fetchCategories = async () => {
  const res = await categoryService.getList()
  if (res.success && res.data) categoryOptions.value = res.data.map(c => ({ label: c.name, value: c.id }))
}
const fetchSubCategories = async (categoryId: number) => {
  const res = await subCategoryService.getByCategoryId(categoryId)
  subCategoryOptions.value = res.success && res.data ? res.data.map(s => ({ label: s.name, value: s.id })) : []
}
const onCategoryCreated = async () => {
  await fetchCategories()
  const last = categoryOptions.value[categoryOptions.value.length - 1]
  if (last) selectedCategoryId.value = last.value
}
const onSubCategoryCreated = async () => {
  if (!selectedCategoryId.value) await fetchCategories()
  if (selectedCategoryId.value) await fetchSubCategories(Number(selectedCategoryId.value))
  const last = subCategoryOptions.value[subCategoryOptions.value.length - 1]
  if (last) form.subCategoryId = last.value
}

watch(selectedCategoryId, async (id) => {
  form.subCategoryId = undefined
  subCategoryOptions.value = []
  if (id) await fetchSubCategories(Number(id))
})

const unitOptions = INVENTORY_UNITS.map(u => ({ label: u as string, value: u as string }))
const branchList = ref<{ id: number, name: string }[]>([])

const availableLabelKeys = ref<string[]>([])
const labels = ref<{ key: string, value: string }[]>([])
const addLabel = () => { labels.value.push({ key: '', value: '' }) }

const attachments = ref<Attachment[]>([])
const attachmentIds = ref<number[]>([])

interface VariantRow { name: string, code: string, stock: Record<number, { new: number, used: number }> }
const variants = ref<VariantRow[]>([])
const makeStock = () => Object.fromEntries(branchList.value.map(b => [b.id, { new: 0, used: 0 }]))
const addVariant = () => { variants.value.push({ name: '', code: '', stock: makeStock() }) }

// ── Photo ─────────────────────────────────────────────────────────────
const fileInput = ref<HTMLInputElement | null>(null)
const previewUrl = ref<string | null>(null)
const isUploading = ref(false)
const showCamera = ref(false)

const triggerFileInput = () => fileInput.value?.click()
const uploadFile = async (file: File) => {
  previewUrl.value = URL.createObjectURL(file)
  isUploading.value = true
  try {
    const res = await inventoryService.uploadImage(file)
    if (res.success && res.data) { form.image = res.data.path }
    else { toast.add({ title: res.message || 'Upload failed', color: 'error', icon: 'i-lucide-circle-alert' }); previewUrl.value = null }
  } finally {
    isUploading.value = false
  }
}
const onFileChange = (e: Event) => { const f = (e.target as HTMLInputElement).files?.[0]; if (f) uploadFile(f) }
const onCaptured = (file: File) => uploadFile(file)
const removeImage = () => { form.image = null; previewUrl.value = null }

const isSubmitting = ref(false)
const onSubmit = async () => {
  isSubmitting.value = true
  try {
    const payloadVariants: InventoryVariantInput[] = variants.value
      .filter(v => v.name.trim())
      .map(v => ({
        name: v.name.trim(),
        code: v.code.trim() || null,
        initialStock: branchList.value
          .map(b => ({ branchId: b.id, new: Number(v.stock[b.id]?.new) || 0, used: Number(v.stock[b.id]?.used) || 0 }))
          .filter(s => s.new > 0 || s.used > 0)
      }))

    const res = await inventoryService.create({
      name: form.name,
      code: form.code || null,
      description: form.description || null,
      image: form.image,
      unit: form.unit || 'Pcs',
      subCategoryId: form.subCategoryId ?? null,
      labels: labels.value.filter(l => l.key.trim() && l.value.trim()),
      variants: payloadVariants,
      attachmentIds: attachmentIds.value,
    })
    if (res.success) {
      toast.add({ title: t('pages.inventory.create.success'), color: 'success', icon: 'i-lucide-circle-check' })
      navigateTo('/inventory')
    } else {
      toast.add({ title: res.message || 'Error occurred', color: 'error', icon: 'i-lucide-circle-alert' })
    }
  } finally {
    isSubmitting.value = false
  }
}

onMounted(async () => {
  const [b, keys] = await Promise.all([branchService.getList(), inventoryService.getLabelKeys(), fetchCategories()])
  if (b.success && b.data) branchList.value = b.data.map(x => ({ id: x.id, name: x.name }))
  if (keys.success && keys.data) availableLabelKeys.value = keys.data
})
</script>
