<template>
  <div class="space-y-6">
    <Header :title="$t('pages.inventory.create.title')" :description="$t('pages.inventory.create.description')" />

    <UCard class="w-full">
      <div class="w-full mb-4">
        <UButton :label="$t('common.back')" to="/inventory" color="neutral" icon="i-lucide-arrow-left" variant="link" />
      </div>

      <UForm id="inv-create-form" :schema="schema" :state="form" @submit="onSubmit">
        <div class="grid grid-cols-1 md:grid-cols-3 gap-x-6 gap-y-4">

          <!-- ═══ Column 1: Photo ═══ -->
          <div class="space-y-4">
            <div>
              <div class="flex justify-between mb-1.5">
                <label class="text-sm font-medium text-neutral-700">{{ $t('pages.inventory.item.photo') }}</label>
                <UButton icon="i-lucide-camera" color="primary" variant="soft" size="xs" @click="() => { showCamera = true }">{{ $t('pages.asset.create.takePhoto') }}</UButton>
              </div>
              <div v-if="previewUrl" class="relative inline-block w-full aspect-square">
                <NuxtImg :src="previewUrl" class="w-full h-full rounded-lg object-cover border border-neutral-200" />
                <UButton icon="i-lucide-x" color="error" variant="solid" size="xs" class="absolute top-1 right-1 rounded-full" @click="removeImage" />
              </div>
              <div v-else class="flex flex-col items-center justify-center w-full aspect-square border-2 border-dashed border-neutral-200 rounded-lg cursor-pointer hover:border-primary transition-colors" @click="triggerFileInput">
                <UIcon name="i-lucide-upload" class="w-8 h-8 text-neutral-400 mb-2" />
                <span class="text-sm text-neutral-500">{{ $t('pages.asset.create.dropImage') }}</span>
                <span class="text-xs text-neutral-400 mt-1">{{ $t('pages.asset.create.imageHint') }}</span>
              </div>
              <div v-if="isUploading" class="mt-2 flex items-center gap-2 text-sm text-neutral-500">
                <UIcon name="i-lucide-loader-2" class="w-4 h-4 animate-spin" /> {{ $t('pages.asset.create.uploading') }}
              </div>
              <input ref="fileInput" type="file" class="hidden" accept="image/*" @change="onFileChange">
              <CameraModal v-model="showCamera" @captured="onCaptured" />
            </div>

            <AttachmentManager v-model="attachments" @change="(ids) => { attachmentIds = ids }" />
          </div>

          <!-- ═══ Column 2: Content ═══ -->
          <div class="space-y-4">
            <UFormField :label="$t('common.name')" name="name" required>
              <UInput v-model="form.name" :placeholder="$t('pages.inventory.create.namePlaceholder')" class="w-full" />
            </UFormField>

            <UFormField :label="$t('common.code')" name="code">
              <div class="flex items-center gap-2">
                <UInput v-model="form.code" :placeholder="$t('common.autoGenerated')" class="w-full" />
                <UButton icon="i-lucide-scan" size="sm" color="neutral" variant="soft" square :title="$t('pages.inventory.create.scan')" @click="() => { openScanner({ kind: 'item' }) }" />
              </div>
            </UFormField>

            <UFormField :label="$t('common.category')" name="categoryId" required>
              <div class="flex items-center gap-2">
                <USelectMenu v-model="selectedCategory" :items="categoryOptions" searchable :searchable-placeholder="$t('pages.asset.create.searchCategory')" :placeholder="$t('pages.asset.create.selectCategory')" class="w-full" />
                <UButton icon="i-lucide-plus" color="primary" variant="soft" size="sm" square @click="() => { showAddCategory = true }" />
              </div>
            </UFormField>

            <UFormField :label="$t('common.subCategory')" name="subCategoryId" required>
              <div class="flex items-center gap-2">
                <USelectMenu v-model="selectedSubCategory" :items="subCategoryOptions" searchable :searchable-placeholder="$t('pages.asset.create.searchSubCategory')" :placeholder="$t('pages.asset.create.selectSubCategory')" :disabled="!form.categoryId" class="w-full" />
                <UButton icon="i-lucide-plus" color="primary" variant="soft" size="sm" square @click="() => { showAddSubCategory = true }" />
              </div>
            </UFormField>

            <UFormField :label="$t('pages.inventory.unit.label')" name="unit" required>
              <USelectMenu v-model="form.unit" :items="unitOptions" value-key="value" :placeholder="$t('pages.inventory.unit.placeholder')" class="w-full" />
            </UFormField>

            <UFormField :label="$t('common.description')" name="description">
              <UTextarea v-model="form.description" :placeholder="$t('common.enterDescription')" class="w-full" :rows="3" />
            </UFormField>

            <div>
              <div class="flex items-center justify-between mb-1.5">
                <label class="text-sm font-medium text-neutral-700">{{ $t('pages.inventory.item.labels') }}</label>
                <UButton icon="i-lucide-plus" color="primary" variant="soft" size="xs" @click="addLabel">{{ $t('common.add') }}</UButton>
              </div>
              <div v-if="labels.length === 0" class="text-sm text-neutral-400 py-3 text-center border border-dashed border-neutral-200 rounded-lg">{{ $t('pages.inventory.create.noLabels') }}</div>
              <div v-else class="space-y-2">
                <div v-for="(label, i) in labels" :key="i" class="flex items-center gap-2">
                  <UInputMenu v-model="label.key" :items="availableLabelKeys" placeholder="Key" class="w-full" />
                  <UInput v-model="label.value" placeholder="Value" class="w-full" />
                  <UButton icon="i-lucide-trash" color="error" variant="soft" size="sm" square @click="() => { labels.splice(i, 1) }" />
                </div>
              </div>
            </div>
          </div>

          <!-- ═══ Column 3: Variants ═══ -->
          <div class="space-y-3">
            <div class="flex items-center justify-between">
              <label class="text-sm font-medium text-neutral-700 flex items-center gap-1.5">
                {{ $t('pages.inventory.variant.title') }}
              </label>
              <div class="flex items-center gap-1.5">
                <UButton icon="i-lucide-scan" color="neutral" variant="soft" size="xs" @click="() => { openScanner({ kind: 'multi' }) }">{{ $t('pages.inventory.create.multiScan') }}</UButton>
                <UButton icon="i-lucide-plus" color="primary" variant="soft" size="xs" @click="addVariant">{{ $t('pages.inventory.variant.add') }}</UButton>
              </div>
            </div>
            <div v-if="form.variants.length === 0" class="text-sm text-neutral-400 py-6 text-center border-2 border-dashed border-neutral-200 rounded-lg">{{ $t('pages.inventory.create.noVariants') }}</div>
            <div v-else class="space-y-3">
              <div v-for="(v, vi) in form.variants" :key="vi" class="p-3 rounded-lg border border-neutral-200 space-y-2.5">
                <div class="flex items-start gap-2">
                  <!-- Variant image -->
                  <div class="shrink-0">
                    <div v-if="v.imagePreview || v.image" class="relative w-32 h-32">
                      <NuxtImg :src="v.imagePreview || v.image || ''" class="w-full h-full rounded-md object-cover border border-neutral-200" />
                      <UButton icon="i-lucide-x" color="error" variant="solid" size="xs" class="absolute -top-1.5 -right-1.5 rounded-full" @click="() => removeVariantImage(vi)" />
                    </div>
                    <label v-else class="w-32 h-32 flex flex-col items-center justify-center border-2 border-dashed border-neutral-200 rounded-md cursor-pointer hover:border-primary transition-colors">
                      <UIcon v-if="!v.uploading" name="i-lucide-image-plus" class="w-5 h-5 text-neutral-400" />
                      <UIcon v-else name="i-lucide-loader-2" class="w-5 h-5 text-neutral-400 animate-spin" />
                      <input type="file" class="hidden" accept="image/*" @change="(e) => onVariantFile(vi, e)">
                    </label>
                  </div>
                  <div class="flex flex-col gap-2 flex-1">
                    <div class="flex items-center gap-2">
                      <UFormField :label="$t('common.name')" :name="`variants.${vi}.name`" class="flex-1" required>
                        <UInput v-model="v.name" :placeholder="$t('pages.inventory.create.variantName')" class="w-full" />
                      </UFormField>
                      <UButton icon="i-lucide-trash" color="error" variant="soft" size="sm" square class="mt-6" @click="() => { form.variants.splice(vi, 1) }" />
                    </div>
                    <div>
                      <UFormField :label="$t('common.code')" :name="`variants.${vi}.code`">
                        <div class="flex items-center gap-2">
                          <UInput v-model="v.code" :placeholder="$t('pages.inventory.variant.codePlaceholder')" class="w-full" />
                          <UButton icon="i-lucide-scan" size="sm" color="neutral" variant="soft" square :title="$t('pages.inventory.create.scan')" @click="() => { openScanner({ kind: 'variant', index: vi }) }" />
                        </div>
                      </UFormField>
                    </div>
                  </div>
                </div>
                <UFormField :label="$t('common.description')" :name="`variants.${vi}.description`">
                  <UTextarea v-model="v.description" :rows="2" :placeholder="$t('common.enterDescription')" class="w-full" />
                </UFormField>
              </div>
            </div>
          </div>
        </div>

        <div class="flex justify-end gap-2 pt-4 mt-6 border-t border-neutral-100">
          <UButton type="button" color="neutral" variant="outline" to="/inventory">{{ $t('common.cancel') }}</UButton>
          <UButton type="submit" color="primary" variant="outline" :loading="isSubmitting && submitMode === 'another'" @click="() => { submitMode = 'another' }">{{ $t('common.saveAndCreateAnother') }}</UButton>
          <UButton type="submit" color="primary" :loading="isSubmitting && submitMode === 'save'" @click="() => { submitMode = 'save' }">{{ $t('common.save') }}</UButton>
        </div>
      </UForm>
    </UCard>

    <CategoryAddModal v-model="showAddCategory" @created="onCategoryCreated" />
    <SubCategoryAddModal v-model="showAddSubCategory" @created="onSubCategoryCreated" />
    <AssetScannerModal v-model="showScanner" :auto-close="scanAutoClose" @scanned="onScanned" />
  </div>
</template>

<script setup lang="ts">
import { z } from 'zod'
import { inventoryService } from '~/services/inventory-service'
import { categoryService } from '~/services/category-service'
import { subCategoryService } from '~/services/sub-category-service'
import type { InventoryVariantInput } from '~/types/inventory'
import type { Attachment } from '~/types/attachment'

definePageMeta({ layout: 'dashboard' })

const { t } = useI18n()
const toast = useToast()

interface VariantRow { name: string, code: string, image: string | null, description: string, imagePreview?: string | null, uploading?: boolean }

const schema = z.object({
  name: z.string().trim().min(1, t('common.nameRequired')),
  categoryId: z.number({ message: t('pages.inventory.create.categoryRequired') }).int().positive(t('pages.inventory.create.categoryRequired')),
  subCategoryId: z.number({ message: t('pages.inventory.create.subCategoryRequired') }).int().positive(t('pages.inventory.create.subCategoryRequired')),
  unit: z.string().trim().min(1, t('pages.inventory.create.unitRequired')),
  variants: z.array(z.object({
    name: z.string().trim().min(1, t('pages.inventory.create.variantNameRequired')),
    code: z.string().trim().max(50, t('pages.inventory.create.variantCodeMax')).optional().or(z.literal(''))
  }))
})
const form = reactive<{ name: string, code: string, description: string, image: string | null, unit: string, categoryId?: number, subCategoryId?: number, variants: VariantRow[] }>({
  name: '', code: '', description: '', image: null, unit: 'Pcs', categoryId: undefined, subCategoryId: undefined, variants: []
})

// ── Category / sub-category (with inline add, like asset) ──────────────
const categoryOptions = ref<{ label: string, value: number }[]>([])
const subCategoryOptions = ref<{ label: string, value: number }[]>([])
const showAddCategory = ref(false)
const showAddSubCategory = ref(false)

const selectedCategory = computed({
  get: () => categoryOptions.value.find(c => c.value === form.categoryId),
  set: (val) => { form.categoryId = val?.value }
})
const selectedSubCategory = computed({
  get: () => subCategoryOptions.value.find(s => s.value === form.subCategoryId),
  set: (val) => { form.subCategoryId = val?.value }
})

const fetchCategories = async () => {
  const res = await categoryService.getList()
  if (res.success && res.data) categoryOptions.value = res.data.map(c => ({ label: c.name, value: c.id }))
}
const fetchSubCategories = async (categoryId: number) => {
  const res = await subCategoryService.getByCategoryId(categoryId)
  subCategoryOptions.value = res.success && res.data ? res.data.map(s => ({ label: s.name, value: s.id })) : []
}
const onCategoryCreated = async () => {
  await fetchCategories()
  const last = categoryOptions.value[categoryOptions.value.length - 1]
  if (last) form.categoryId = last.value
}
const onSubCategoryCreated = async () => {
  if (!form.categoryId) await fetchCategories()
  if (form.categoryId) await fetchSubCategories(Number(form.categoryId))
  const last = subCategoryOptions.value[subCategoryOptions.value.length - 1]
  if (last) form.subCategoryId = last.value
}

watch(() => form.categoryId, async (id) => {
  form.subCategoryId = undefined
  subCategoryOptions.value = []
  if (id) await fetchSubCategories(Number(id))
})

const unitOptions = INVENTORY_UNITS.map(u => ({ label: u as string, value: u as string }))

const availableLabelKeys = ref<string[]>([])
const labels = ref<{ key: string, value: string }[]>([])
const addLabel = () => { labels.value.push({ key: '', value: '' }) }

const attachments = ref<Attachment[]>([])
const attachmentIds = ref<number[]>([])

const newVariant = (name = '', code = ''): VariantRow => ({ name, code, image: null, description: '', imagePreview: null, uploading: false })
const addVariant = () => { form.variants.push(newVariant()) }

// Per-variant image upload.
const onVariantFile = async (index: number, e: Event) => {
  const file = (e.target as HTMLInputElement).files?.[0]
  const v = form.variants[index]
  if (!file || !v) return
  v.imagePreview = URL.createObjectURL(file)
  v.uploading = true
  try {
    const res = await inventoryService.uploadImage(file)
    if (res.success && res.data) { v.image = res.data.path }
    else { toast.add({ title: res.message || 'Upload failed', color: 'error', icon: 'i-lucide-circle-alert' }); v.imagePreview = null }
  } finally {
    v.uploading = false
  }
}
const removeVariantImage = (index: number) => {
  const v = form.variants[index]
  if (v) { v.image = null; v.imagePreview = null }
}

// ── Barcode scanning (single for item/variant code, multi to add variants) ──
type ScanTarget = { kind: 'item' } | { kind: 'variant', index: number } | { kind: 'multi' }
const showScanner = ref(false)
const scanAutoClose = ref(true)
const scanTarget = ref<ScanTarget>({ kind: 'item' })

const openScanner = (target: ScanTarget) => {
  scanTarget.value = target
  scanAutoClose.value = target.kind !== 'multi'
  showScanner.value = true
}
const onScanned = (code: string) => {
  const trimmed = code.trim()
  if (!trimmed) return
  const target = scanTarget.value
  if (target.kind === 'item') {
    form.code = trimmed
  } else if (target.kind === 'variant') {
    const v = form.variants[target.index]
    if (v) v.code = trimmed
  } else {
    // Multi-scan: fill the first variant with an empty code, otherwise add a new one.
    const empty = form.variants.find(v => !v.code.trim())
    if (empty) { empty.code = trimmed; if (!empty.name.trim()) empty.name = trimmed }
    else form.variants.push(newVariant(trimmed, trimmed))
  }
}

// ── Photo ─────────────────────────────────────────────────────────────
const fileInput = ref<HTMLInputElement | null>(null)
const previewUrl = ref<string | null>(null)
const isUploading = ref(false)
const showCamera = ref(false)

const triggerFileInput = () => fileInput.value?.click()
const uploadFile = async (file: File) => {
  previewUrl.value = URL.createObjectURL(file)
  isUploading.value = true
  try {
    const res = await inventoryService.uploadImage(file)
    if (res.success && res.data) { form.image = res.data.path }
    else { toast.add({ title: res.message || 'Upload failed', color: 'error', icon: 'i-lucide-circle-alert' }); previewUrl.value = null }
  } finally {
    isUploading.value = false
  }
}
const onFileChange = (e: Event) => { const f = (e.target as HTMLInputElement).files?.[0]; if (f) uploadFile(f) }
const onCaptured = (file: File) => uploadFile(file)
const removeImage = () => { form.image = null; previewUrl.value = null }

const isSubmitting = ref(false)
const submitMode = ref<'save' | 'another'>('save')

const resetForm = () => {
  Object.assign(form, {
    name: '', code: '', description: '', image: null, unit: 'Pcs', categoryId: undefined, subCategoryId: undefined, variants: [],
  })
  subCategoryOptions.value = []
  previewUrl.value = null
  labels.value = []
  attachments.value = []
  attachmentIds.value = []
}

const onSubmit = async () => {
  isSubmitting.value = true
  try {
    const payloadVariants: InventoryVariantInput[] = form.variants
      .filter(v => v.name.trim())
      .map(v => ({ name: v.name.trim(), code: v.code.trim() || null, image: v.image, description: v.description.trim() || null }))

    const res = await inventoryService.create({
      name: form.name,
      code: form.code || null,
      description: form.description || null,
      image: form.image,
      unit: form.unit || 'Pcs',
      subCategoryId: form.subCategoryId ?? null,
      labels: labels.value.filter(l => l.key.trim() && l.value.trim()),
      variants: payloadVariants,
      attachmentIds: attachmentIds.value,
    })
    if (res.success) {
      toast.add({ title: t('pages.inventory.create.success'), color: 'success', icon: 'i-lucide-circle-check' })
      if (submitMode.value === 'another') {
        resetForm()
      } else {
        navigateTo('/inventory')
      }
    } else {
      toast.add({ title: res.message || 'Error occurred', color: 'error', icon: 'i-lucide-circle-alert' })
    }
  } finally {
    isSubmitting.value = false
  }
}

onMounted(async () => {
  const [keys] = await Promise.all([inventoryService.getLabelKeys(), fetchCategories()])
  if (keys.success && keys.data) availableLabelKeys.value = keys.data
})
</script>
